---
title: "Data Wrangling"
date: 9/18/18
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)

library(tidyverse)
```

## Import FAS csv files

Import csv file and format names

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```


## Example

Loading in new data set

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Look at Data

Look at litters data

```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)
```

View function allows you to view entire data set in console, could cause errors in code chunks.

```{r}
head(pups_data)
tail(pups_data)

skimr::skim(pups_data)
```


## Other File Formats

Read in MLB data: Excel

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")

mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
```

Read in Pulse Data: SAS 

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

